spring:
  application:
    name: oauth2-server

server:
  port: 31031
  servlet:
    context-path: /oauth2-authorization
    
logging:
  file: /logs/oauth2-authorization.log
  level:
    org:
      springframework:
        web: debug
        security: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:40002/server-naming/eureka