spring:
  application:
    name: security-utilities

server:
  port: 20011
  servlet:
    context-path: /sec-utils
    
logging:
  file: /logs/security-utilities.log
  level:
    org:
      springframework:
        web: debug
        security: debug
    
security:
  oauth2:
    resource:
      clientId: ResourceSecurityUtilities
      clientSecret: secret
      checkTokenEndpointUrl: http://localhost:6010/oauth2-authorization/oauth/check_token

app-config:
  shaAlgo: SHA-1
