spring:
  application:
    name: server-naming
    
logging:
  level:
    com.netflix: debug
    
server:
  port: 40002
  
eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false
