spring:
  application:
    name: vertx-multiple-tables

#hasher:
#  ribbon:
#    listOfServers: http://localhost:31012,http://localhost:31112

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:40002/server-naming/eureka

logging:
  level:
    com.netflix: debug

app-config :
  port : 31011
  headerContentType : content-type
  headerApplicationJson : application/json; charset=utf-8
  addressUser: samples.dataAccess.user
  addressMarketInfo: samples.dataAccess.marketInfo
  
db-config:
  url: jdbc:h2:mem:sample
  driver_class: org.h2.Driver
#  user: test
#  password: easy1111
  
message:
  ins:
    failed:
      internal-error: Creation failed due to internal error.

