spring:
  application:
    name: zuul-gateway
  main:
    allow-bean-definition-overriding:true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:40002/server-naming/eureka
  instance:
    preferIpAddress: true
    
server:
  port: 40003
  servlet:
    context-path: /zuul-gateway
    
