spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: ${user.home}/git/cloud/config-server/src/main/resources/config-repo
  
server:
   port: 40001
   servlet:
     context-path: /config-server
     